stages:

  preprocess:

    cmd: python -m training.src.preprocessing

    deps:
      - training/src/preprocessing.py
      - data/raw/customer_churn.csv
      - params.yaml

    outs:
      - data/processed/data.pkl
      - models/preprocessor.pkl

  train:

    cmd: python -m training.src.train

    deps:
      - training/src/train.py
      - data/processed/data.pkl
      - params.yaml

    outs:
      - models/model.pkl

  drift_detection:

    cmd: python -m monitoring.drift

    deps:
      - monitoring/drift.py

    outs:
      - monitoring/reports/drift_report.html
      - monitoring/reports/drift_result.json